---
title: "Assignment 2"
author: "Tseme Botlhe 201802398"
date: "07/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Q1 

```{r}
 ab=c("a","b")
 rep(ab,4)
 rep(ab,each = 4)
 rep(ab,each = 2, 2)

```



# Q2

*A*

```{r}
level=c("Tertiary","Primary","None","BGCSE","JC","JC","BGCSE" ,"Tertiary","JC", "None" ,"BGCSE","BGCSE","Primary","Tertiary","JC","BGCSE" ,"Tertiary","BGCSE","Primary","Tertiary")


education=factor(level,levels=c("None","Primary","JC","BGCSE","Tertiary"), ordered=TRUE )

education
```

*B*

Number of students whose parents’ highest level of education are BGCSE or above


```{r}
x = table(education > "JC")
as.numeric(x["TRUE"])

```


# Q3


```{r}
A=matrix(c(2,1,2,2,1,-1,2,1,4,3,3,3,3,1,-2,4), nrow=4,ncol=4 ,byrow = TRUE)
b=matrix(c(2,6,1,-7), nrow=4, ncol=1 ,byrow=TRUE)
A
b
solve(A,b)
```

# Q4

*A*


```{r}
names=c("KABO","DAVID","LERATO","MMABATHO")
Surname=c("MALOME","APRIL","SEBAGA","KGOSI")
id=c("202001428","20200090","202000178","202005533")

names
Surname
id
```

*B*

```{r}
nam = substr(names, 1, 3)
sur = substr(Surname, 1, 3)
n_last = 4
id_ = substr(id, nchar(id) - n_last + 1, nchar(id))
paste(nam, sur, id_, sep = '')
```

# Q5



```{r}
 subject=c("CSI","STA","CSI","FIN","CSI","CSI")
 code=c("341","272","315","302","352","392")
 CA=c(80,90,70,80,90,90)
 EXM=c(85,95,80,95,100,100)
 
```

*A*

```{r}
paste(nam, sur, id_, sep = '')
coursecode = paste(subject, code, sep = '')
```

*B*

```{r}
FM = (CA * 0.4) +  (EXM * 0.6)

schedule = data.frame(coursecode, FM) 
schedule

```

